TRB changes for the connection between DQM and DF
DUNE-DAQ/dfmodules pull request #140
Opened 2022-02-28 15:29 UTC by jmcarcell

Goes together with 

- https://github.com/DUNE-DAQ/dqm/pull/81
- https://github.com/DUNE-DAQ/daqconf/pull/3
- https://github.com/DUNE-DAQ/appfwk/pull/215
- https://github.com/DUNE-DAQ/dfmessages/pull/44 (already merged, not in the nightly until tomorrow)

2022-02-28 16:50 UTC, mroda88 requested changes
@jmcarcell can you remove the ipm header? It's a bit nasty here and we don't really need it.

2022-02-28 16:50 UTC, mroda88 commented on plugins/TriggerRecordBuilder.hpp
> +  //std::map<std::string,dfmessages::TRMonRequest> m_mon_requests;
Please get rid of the comment. I would have left it, but since I'm making the comment about the dependency let's fix this as well.

2022-03-01 14:28 UTC, mroda88 approved these changes
fantastic, thanks!

2022-03-01 14:33 UTC, jmcarcell commented
Actually `ipm` is used in the callback that dispatches the requests from DQM so I'm adding it back, saw it right after pushing the previous one but you were too fast :)

2022-03-01 14:35 UTC, mroda88 approved these changes
No worries

2022-03-03 18:22 UTC, merged